name: Run Tests on Push

on:
  push:
    branches: ["main"]

jobs:
  tests:
    name: Tests
    if: github.event.head_commit.author.name != 'github-classroom[bot]'
    runs-on: self-hosted
    env:
      TESTS_REPO_URL: https://github.com/FMI-SoftwareEngineering-23-24/tests-homework-1
    steps:
      - uses: actions/checkout@v4

      - name: Make temporary directory for tests
        id: temp
        run: echo "path=$(mktemp -d)" >> $GITHUB_OUTPUT

      - name: Download tests
        run: |
          git clone "$TESTS_REPO_URL" "${{ steps.temp.outputs.path }}"
          chmod +x ${{ steps.temp.outputs.path }}/tests.sh

      - name: Run tests
        run: ${{ steps.temp.outputs.path }}/tests.sh

      - name: Upload results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: test-results/
