name: Remote Sync

on:
  repository_dispatch:
    types: [remote-sync]

jobs:
  merge:
    runs-on: self-hosted
    env:
      TEMPLATE_REPO_URL: https://github.com/FMI-SoftwareEngineering-23-24/homework-1
    steps:
      - uses: actions/checkout@v4

      - name: Make directory for template repository
        id: temp
        run: |
          echo "path=$(mktemp -d)" >> $GITHUB_OUTPUT

      - name: Download template repository
        run: |
          git config --global user.name "Remote Sync"
          git config --global user.email "remote-sync@dev.null"
          git clone "$TEMPLATE_REPO_URL" "${{ steps.temp.outputs.path }}"

      - name: Copy the new files from the template repository
        run: |
          shopt -s dotglob
          rm -rf "${{ steps.temp.outputs.path }}"/.git
          rm -rf "${{ steps.temp.outputs.path }}"/.github
          mv -f "${{ steps.temp.outputs.path }}"/* ./
          rm -rf "${{ steps.temp.outputs.path }}"

      - name: Check if there are any new files
        id: clear
        run: |
          echo "working_tree_clear<<EOF" >> $GITHUB_OUTPUT
          echo "$(git status --porcelain)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Push changes
        if: steps.clear.outputs.working_tree_clear != ''
        run: |
          git add .
          git commit -m "Update repository from template"
          git push origin main
